update files
Abel-desu/Portfolio-setup-and-mobile-version-skeleton pull request #11
Opened 2022-05-17 12:51 UTC by Abel-desu

initialize js for popup

2022-05-17 13:35 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @Abel-desu,

Nice job, you are almost there.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-17 13:35 UTC, Omar-Muhamad commented on script.js
> +  header.appendChild(window);
- [ ] Please add the correct style for your mobile menu by positioning every element in the right place like the given design: 
- The close button suppose to be higher at the top and kindly make it bigger and add the correct color to it.
- and the nav links suppose to be lower than that.
So kindly fix that and try to stick as much as possible to the given Figma design.

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/168822799-89c70cee-30e6-4746-ae73-a2cd80861bfa.png)  | ![image](https://user-images.githubusercontent.com/68796232/168822529-a0d73d07-05aa-4696-a5e3-3ea05a043a51.png)  |

2022-05-17 13:35 UTC, Omar-Muhamad commented on script.js
> +    window.removeChild(popup);
- [ ] When I click on any nav link it supposes to redirect me to the right sect on the page and closes the mobile menu that doesn't happen here in your app So please fix that.

2022-05-18 09:42 UTC, thecodechaser approved these changes
## STATUS: APPROVED 🟢

## Hi @Abel-desu👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

## Optional suggestions
- [ ] Please use camelcase menu options and increase the gap between mobile menu options. It will make your project looks more professional.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-20 09:29 UTC, merged