My portfolio
Abel-desu/Portfolio-setup-and-mobile-version-skeleton pull request #2
Opened 2022-04-29 09:25 UTC by Abel-desu

adding some features on it

2022-04-29 11:19 UTC, roshan-bajgain requested changes
Hi there, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/KG5KpLlr1UEPvwgkiM/giphy.gif"/>

<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight :tada: :champagne: 
- Nice PR description and title :+1: 
- Nice README file :heavy_check_mark:
- No linter error :heavy_check_mark:
- GitHub flow is followed :+1:


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-29 11:19 UTC, roshan-bajgain commented on index.html
> +          </div>
- [ ] The button ` See project` should be a link or button tag, and follow the button styling: Active, Hover, and Pressed (see design). Kindly implement it
### Figma button design
![figma](https://user-images.githubusercontent.com/81727988/165932664-35948504-c2b3-4372-b10e-47c7cadc81e2.png)

2022-04-29 11:19 UTC, roshan-bajgain commented on index.html
> +          </div>
- [ ] The button ` See project` should be a link or button tag, and follow the button styling: Active, Hover, and Pressed (see design). Kindly implement it
### Figma button design
![figma](https://user-images.githubusercontent.com/81727988/165932664-35948504-c2b3-4372-b10e-47c7cadc81e2.png)

2022-04-29 11:19 UTC, roshan-bajgain commented on index.html
> +          </div>
- [ ] The button ` See project` should be a link or button tag, and follow the button styling: Active, Hover, and Pressed (see design). Kindly implement it
### Figma button design
![figma](https://user-images.githubusercontent.com/81727988/165932664-35948504-c2b3-4372-b10e-47c7cadc81e2.png)

2022-04-29 11:19 UTC, roshan-bajgain commented on index.html
> +      </div>
- [ ] The button ` See project` should be a link or button tag, and follow the button styling: Active, Hover, and Pressed (see design). Kindly implement it
### Figma button design
![figma](https://user-images.githubusercontent.com/81727988/165932664-35948504-c2b3-4372-b10e-47c7cadc81e2.png)

2022-04-29 11:19 UTC, roshan-bajgain commented on index.html
> +        </div>
- [ ] Kindly wrap this `p` tag with `hx` tag for HTML  good practice.

2022-04-29 11:19 UTC, roshan-bajgain commented on index.html
> +      </div>
- [ ] The button ` Get my Resume` should be a link or button tag, and follow the button styling: Active, Hover, and Pressed (see design). Kindly implement it
### Figma button design
![figma](https://user-images.githubusercontent.com/81727988/165932664-35948504-c2b3-4372-b10e-47c7cadc81e2.png)

2022-04-29 11:19 UTC, roshan-bajgain commented on index.html
> +            <span class="down-angle"><i class="fa-solid fa-angle-down"></i></span>
- [ ] Kindly wrap this `languages` with ul and put this `language` in li tag for better practice

2022-04-29 11:19 UTC, roshan-bajgain commented on index.html
> +          </div>
- [ ] I would suggest you to stick as much as possible with Figma design.
- [ ] Kindly implement in all the section.
### your design
![his](https://user-images.githubusercontent.com/81727988/165934560-12116893-a05f-4e7a-b284-52a8dd95a1b4.png)
### Figma design
![figma-design](https://user-images.githubusercontent.com/81727988/165934632-79693f3b-d862-4376-9f5b-b1a95755729d.png)

2022-04-30 15:14 UTC, smunozmo approved these changes
Hi @Abel-desu, 👋 

## Highlights 👏 

- Great work using the right GitHub Flow.
- Your README looks professional, well done!
- Commits are descriptive, good work.
- Linters are working properly, great job!

Your project is complete!  There is nothing else to say other than... it's time to merge it! 🚀 
Very nice work, congratulations! 🎉 

### APPROVED! 💯  💯  💯 

<img src="https://media4.giphy.com/media/cFkiFMDg3iFoI/giphy.gif"/>


Cheers and Happy coding! 🤓 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-03 09:56 UTC, merged